[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # Estos valores son solo para engañar al build, los reales irán en el panel de Netlify
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.next/server/pages/:splat"
  status = 200
