[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración para evitar problemas con las rutas de Next.js
[[redirects]]
  from = "/*"
  to = "/.next/server/pages/:splat"
  status = 200
