"use client";
import { FormEvent, useState } from "react"; import Link from "next/link"; import { ArrowRight, Lock } from "lucide-react"; import { supabase } from "@/lib/supabase";
export default function ResetPasswordPage() {
 const [password,setPassword]=useState(""); const [confirmation,setConfirmation]=useState(""); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const handleSubmit=async(e:FormEvent)=>{e.preventDefault();setMessage("");setError("");if(password.length<8){setError("La contraseña debe tener al menos 8 caracteres.");return}if(password!==confirmation){setError("Las contraseñas no coinciden.");return}setLoading(true);const {error}=await supabase.auth.updateUser({password});if(error)setError("El enlace no es válido o ya expiró. Solicita una nueva recuperación.");else{setMessage("Contraseña actualizada. Ya puedes ingresar.");setPassword("");setConfirmation("")}setLoading(false)};
 return <main className="min-h-screen bg-[#F8F9FA] px-4 py-8 flex items-center justify-center"><section className="w-full max-w-[420px] rounded-[2rem] border border-gray-200 bg-white p-8 shadow-xl"><div className="mb-8 text-center"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-600 text-white"><Lock size={22}/></div><h1 className="text-2xl font-black uppercase tracking-tight text-gray-950">Nueva contraseña</h1><p className="mt-2 text-sm text-gray-500">Usa mínimo 8 caracteres.</p></div>
 <form onSubmit={handleSubmit} className="space-y-5"><label className="block text-xs font-black uppercase tracking-wide text-gray-700">Nueva contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-2xl border border-gray-300 bg-white p-4 text-sm font-semibold text-gray-900 outline-none focus:border-orange-600 focus:ring-2 focus:ring-orange-100" autoComplete="new-password" required minLength={8}/></label><label className="block text-xs font-black uppercase tracking-wide text-gray-700">Confirmar contraseña<input type="password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="mt-2 w-full rounded-2xl border border-gray-300 bg-white p-4 text-sm font-semibold text-gray-900 outline-none focus:border-orange-600 focus:ring-2 focus:ring-orange-100" autoComplete="new-password" required minLength={8}/></label>
 {message && <p className="rounded-xl bg-green-50 p-3 text-center text-sm font-semibold text-green-700">{message}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-center text-sm font-semibold text-red-700">{error}</p>}<button type="submit" disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-orange-600 p-4 font-black uppercase text-white transition hover:bg-orange-700 disabled:opacity-50">{loading?"Actualizando...":"Cambiar contraseña"} {!loading&&<ArrowRight size={16}/>}</button></form>
 <p className="mt-6 text-center text-sm font-semibold text-gray-600"><Link href="/login" className="text-orange-600 hover:underline">Volver al inicio de sesión</Link></p></section></main>;
}